// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYHdmfMk9--af2moTOYHLfxGjVIansUnI',
    appId: '1:934872460078:web:6099826d655bccd25768bf',
    messagingSenderId: '934872460078',
    projectId: 'weatherapp-f6aaf',
    authDomain: 'weatherapp-f6aaf.firebaseapp.com',
    storageBucket: 'weatherapp-f6aaf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTGmw6Vx3aLqbI8fHV146iNTX9Tyg8SXw',
    appId: '1:934872460078:android:ff0b543b32625bf75768bf',
    messagingSenderId: '934872460078',
    projectId: 'weatherapp-f6aaf',
    storageBucket: 'weatherapp-f6aaf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTAFkzqM7vVWjsNII1Yxm8rM023Wgwiuc',
    appId: '1:934872460078:ios:4e10e2bdef468a2e5768bf',
    messagingSenderId: '934872460078',
    projectId: 'weatherapp-f6aaf',
    storageBucket: 'weatherapp-f6aaf.firebasestorage.app',
    iosBundleId: 'com.example.weatherApplication',
  );

}